version: '3.8'

services:
  meraki-mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meraki-mcp-server
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MERAKI_API_KEY=${MERAKI_API_KEY}
    # If you want to expose the server externally, uncomment the ports section
    # ports:
    #   - "8000:8000"
    volumes:
      # Optional: For development, mount the code directory for hot-reloading
      # - ./:/app
      # For logs persistence
      - ./logs:/app/logs
    # Healthcheck to ensure the server is running properly
    # healthcheck:
    #   test: ["CMD", "uv", "run", "-c", "import socket; socket.socket().connect(('localhost', 8000))"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 5s
    networks:
      - meraki-network

networks:
  meraki-network:
    driver: bridge
